Project3_WebApplication/pizzeria/pizzas/urls.py
"""定义pizzas的URL模式"""
from django.urls import re_path

from . import views

urlpatterns = [
    #homepage
    re_path(r'^$', views.index, name='index'),#第三个实参将这个URL模式的名称指定为index，让我们能够在代码的其他地方引用它。每当需要提供到这个主页的链接时，我们都将使用这个名称，而不编写URL。
    re_path(r'^pizzas/$', views.pizzas, name='pizzas'), 

    re_path(r'^pizzas/(?P<pizza_id>\d+)/$', views.pizza, name='pizza'),  
]

Project3_WebApplication/pizzeria/pizzeria/urls.py
from django.contrib import admin

from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include(('pizzas.urls','pizzas'), namespace = 'pizzas')),
]

Project3_WebApplication/pizzeria/pizzas/models.py
from pyexpat import model
from django.db import models

# Create your models here.
# 定义一个名为Pizza 的模型，它包含字段name，用于存储比萨名称，如Hawaiian和Meat Lovers。
# 定义一个名为Topping 的模型，它包含字段pizza 和name，其中字段pizza 是一个关联到Pizza 的外键，
# 而字段name 用于存储配料，如pineapple、Canadian bacon 和sausage
class Pizza(models.Model):
    name = models.CharField(max_length=20)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        """返回模型的字符串表示"""
        return self.name
        
class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

Project3_WebApplication/pizzeria/pizzas/views.py
from django.shortcuts import render

from .models import Pizza

# Create your views here.
def index(request):
    """主页"""
    return render(request, 'pizzas/index.html')

def pizzas(request): #request: Django从服务器那里收到的request 对象
    """显示所有的主题"""
    pizzas = Pizza.objects.order_by('date_added') #查询数据库——请求提供Topic对象
    context = {'pizzas': pizzas} #定义一个将要发送给模板的上下文:键是我们将在模板中用来访问数据的名称，而值是我们要发送给模板的数据
    return render(request, 'pizzas/pizzas.html', context) #将对象request, 模板的路径，变量context传递给render()

def pizza(request, pizza_id): 
    """显示单个主题及所有的条目"""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('-date_added')
    context = {'pizza': pizza, 'toppings':toppings}
    return render(request, 'pizzas/pizza.html', context)

Project3_WebApplication/pizzeria/pizzas/templates/pizzas/base.html
<p>
  <!-- #标题设置为到主页的链接; 主页的链接后面添加了一个连字符-->
  <a href="{% url 'pizzas:index' %}">Pizzeria</a> -
  <!-- 显示所有主题的页面的链接 -->
  <a href="{% url 'pizzas:pizzas' %}">Pizza</a>
</p>

{% block content %}{% endblock content %}

Project3_WebApplication/pizzeria/pizzas/templates/pizzas/index.html
<!-- Django知道它继承了哪个父模板 -->
{% extends "pizzas/base.html" %}

{% block content %}
<p>Pizza helps you keep track of your learning, for any topic you're
learning about.</p>
{% endblock content %}

Project3_WebApplication/pizzeria/pizzas/templates/pizzas/pizza.html
<!-- 继承base.html -->
{% extends "pizzas/base.html" %}
{% block content %}
<!-- 显示当前主题 -->
<p>Pizza: {{ pizza }}</p>

<p>Toppings:</p>
  <!-- 定义每个条目的项目列表 -->
  <ul>
    <!-- 遍历条目 -->
    {% for topping in toppings %}
      <li>
        <!-- 列出时间戳；"|"模板过滤器：对模板变量值进行修改的函数 -->
        <p>{{ topping.date_added|date:'M d, Y H:i' }}</p>
        <!-- 接下来的一行显示text 的完整；过滤器linebreaks将包含换行符的长条目转换为浏览器能够理解的格式，以免显示为一个不间断的文本块 -->
        <p>{{ topping.text|linebreaks }}</p>
      </li>
    <!-- 打印消息：当前主题还没有条目 -->
    {% empty %}
      <li>
      There are no entries for this topic yet.
      </li>
    {% endfor %}
  </ul>
{% endblock content %}

Project3_WebApplication/pizzeria/pizzas/templates/pizzas/pizzas.html
<!-- 继承base.html -->
{% extends "pizzas/base.html" %}

{% block content %}
<p>Pizzas</p>
  <!-- 这个网页的主体是一个项目列表，其中列出了用户输入的主题。在标准HTML中，项目列表被称为无序列表，用标签<ul></ul> 表示。 -->
  <ul>
    <!-- 将每个主题转换为一个项目列表项 -->
    {% for pizza in pizzas %}
      <!-- 要在模板中打印变量，需要将变量名用双花括号括起来。每次循环时,代码{{ topic }} 都被替换为topic 的当前值。这些花括号不会出现在网页中，它们只是用于告诉Django我们使用了一个模板变量。 -->
      <li>
        <!-- 主题列表中的每个主题都是一个链接，链接到显示相应主题的页面pizza.html，如http://localhost:8000/topics/1/ -->
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
      </li>
      <!-- 告诉Django在列表topics 为空时该怎么办 -->
    {% empty %} 
      <!-- 告诉用户还没有添加任何主题 -->
      <li>No topics have been added yet.</li>
    <!-- 终止for循环 -->
    {% endfor %}
  <!-- 结束项目列表 -->
  </ul>

{% endblock content %}